# Generated by Django 3.1.1 on 2023-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
