# Generated by Django 3.1.1 on 2023-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectionApp', '0002_auto_20230626_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cost',
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10),
        ),
    ]
