# Generated by Django 3.1.1 on 2023-06-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectionApp', '0003_auto_20230626_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=10),
        ),
    ]
