# Generated by Django 3.1.1 on 2023-07-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelectionApp', '0005_auto_20230626_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preferred_room_type',
        ),
    ]
