# Generated by Django 3.1.1 on 2023-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectionApp', '0006_auto_20230717_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
